server.port=${PORT:8080}
spring.application.name=student-network

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/studentnetdb
spring.datasource.username=postgres
spring.datasource.password=santhosh@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
app.jwt.secret=StudentNetworkSuperSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm2024
app.jwt.expiration-ms=86400000

logging.level.com.studentnet=DEBUG
logging.level.org.springframework.security=WARN
